### ISSUE TITLE
Shouldn't be able to run Ruby code

### ISSUE THREAD

**Issue by asterite** [jhass/carc.in#1]
I'm OK with Crystal and C. I'd be fine you add C++, Clojure, Clang, Coffescript, C# and Ceylon. But Ruby... it somehow feels out of place.

**Comment by jhass** [comment]
The site is intended as a general code online evaluator, we can always hide/whitelist (and I actually intended to) stuff when you want to point a crystal-lang.org subdomain to it.

**Comment by asterite** [comment]
Oh, so the "C" in "carc" can also mean "Code"... hmmm... fine :stuck_out_tongue:

**Comment by jhass** [comment]
It's meant as acronym for "Compile and Run Code in", finding a short available domain was hard :P

**Comment by asterite** [comment]
I initially thought it was "Compile and Run Crystal", but "Compile and Run C" (Clojure, etc.) could work too, but Ruby was out of place ;-)

Luckily "Code" works too.
