### ISSUE TITLE
Issue when trying to run this code

### ISSUE THREAD

**Issue by jwoertink** [jhass/carc.in#15]
When I try to run this crystal code:

```crystal
io = IO::Memory.new

IO::ByteFormat::LittleEndian.encode(5, io)

puts io
```

In Brave, it sends me back to the homepage with an empty field. In firefox and safari, it sends me back to the main page with the original code still in. 

Using latest browsers on macOS Catalina compiling crystal 0.32.1

**Comment by jwoertink** [comment]
Looks like @straight-shoota found that `puts Char::ZERO` does the same thing

ref: https://gitter.im/crystal-lang/crystal?at=5e18fadb65540a529af578fc

**Comment by jhass** [comment]
Fun
```
 invalid byte sequence for encoding "UTF8": 0x00 (PQ::PQError)
   from home/carcin/carcin/lib/pg/src/pq/connection.cr:0:7 in 'handle_error'
   from home/carcin/carcin/lib/pg/src/pq/connection.cr:0:0 in 'handle_async_frames'
   from home/carcin/carcin/lib/pg/src/pq/connection.cr:162:7 in 'read'
   from home/carcin/carcin/lib/pg/src/pq/connection.cr:157:7 in 'expect_frame'
   from home/carcin/carcin/lib/pg/src/pq/connection.cr:156:5 in 'match_POST__SLASH_run_requests'
   from home/carcin/carcin/lib/artanis/src/dsl.cr:127:7 in 'call'
   from usr/lib/crystal/http/server/request_processor.cr:255:3 in '->'
   from usr/lib/crystal/fiber.cr:255:3 in 'run'
   from ???

**Comment by jhass** [comment]
For now I just scrub the output. I wish there was a mix of `String#dump` and `String#scrub`  that would replace invalid byte sequences with their escape sequences but leaves everything else intact. Might be a good little toy if somebody feels bored :)

**Comment by jwoertink** [comment]
Awesome! Thanks for that.
