### ISSUE TITLE
XML Tags Not Shown in Code Preview

### ISSUE THREAD

**Issue by kinxer** [jhass/carc.in#16]
When carc.in is given the code
```crystal
puts "<something />"
```
the run output is accurately
```
<something />
```
but the code preview shows
```crystal
puts ""
```

If the tag is expanded and given contents, like
```crystal
puts "<something>something</something>"
```
the run output is still accurate, but the code preview only shows the contents:
```crystal
puts "something"
```

**Comment by oprypin** [comment]
Same root cause as #17 and I think it's fixed
