### ISSUE TITLE
Crystal code syntax highlight

### ISSUE THREAD

**Issue by MakeNowJust** [jhass/carc.in#2]
I added Crystal language definition to highlight.js. https://github.com/isagalaev/highlight.js/pull/921

If highlight.js v8.8.0 is released, you should update highlight.js and fix [it](https://github.com/jhass/carc.in/blob/393d5ed595081bee6356762a2c66c613363626a7/frontend/app/components/source-code.js#L5)

**Comment by jhass** [comment]
Awesome, thank you!

**Comment by jhass** [comment]
Btw if you enjoy this kind of work, [codemirror](https://github.com/codemirror/codemirror) is what I use for the editor ;)

**Comment by MakeNowJust** [comment]
I will try to create crystal mode in codemirror (It's harder work than highlight.js :sob: )

BTW I created [carcin.vim](https://github.com/MakeNowJust/carcin.vim).  This is a carc.in API wrapper for vim. Do you have a problem about using this API?

**Comment by jhass** [comment]
No, as long as it's clear where the results come from it's fine. If you publicize the results, please include the returned `html_url` field.
