### ISSUE TITLE
Download code link

### ISSUE THREAD

**Issue by bcardiff** [jhass/carc.in#3]
I think it would be nice to have a download code link.
It will allow to use carc.in for sharing code in a gist manner.

Thoughts?

**Comment by jhass** [comment]
Mmh, not sure I follow what the download link would provide. Do you mean a raw view like https://gist.githubusercontent.com/jhass/a498e23c4eb8584dea9b/raw/1f9dc08b01d3691a5197c741e0a8029b792d2647/keybase.md ?

**Comment by bcardiff** [comment]
Yes a raw view with, maybe, a Content-Disposition header to force a download .cr file

**Comment by jhass** [comment]
Mmmh, do you have any interface suggestions? I don't feel like there's enough room left next to "New" and "Edit, and also that it's not a common enough action to warrant such common placement.

**Comment by jhass** [comment]
Note the current UI is usable down to about 370px width.

![](http://cloud.aeshna.de/u/mrzyx/screenshots/screenshot_20150904_192529.png)

**Comment by bcardiff** [comment]
I was thinking just a download icon link after the name. Otherwise you need to edit/select all/copy to grab the source.

**Comment by jhass** [comment]
Alright, I went for doing icon buttons to gain enough space for the download button. It looked misplaced anywhere else.

Implemented.

**Comment by bcardiff** [comment]
Thanks :-)
