### ISSUE TITLE
Problem testing network code

### ISSUE THREAD

**Issue by hugoabonizio** [jhass/carc.in#8]
I'm trying to run this example to test the network performance (because in my computer it seems to be a little slow on IO#gets method) but it seems to be impossible to share the result on carc.in, am I right?

https://carc.in/#/r/16wj

This is based on Crystal's examples of tcp server/client.

**Comment by asterite** [comment]
`carc.in` is in a sandbox and connections are disallowed, this is expected behaviour

**Comment by hugoabonizio** [comment]
Even localhost connections?

**Comment by jhass** [comment]
Additionally it's running on a fairly underpowered box at the moment, so its results will most likely not be relevant for your case anyway.

Anyway, yes, network has to stay disabled. It's a syscall filter mainly and that's just to tricky to get right for only allowing localhost connections. Sorry.

**Comment by hugoabonizio** [comment]
OK, thank you.
